# Retail Store Application
# Uses AWS managed services provisioned by Terraform

catalog:
  app:
    persistence:
      provider: mysql
      endpoint: project-bedrock-mysql.cop8qmuak7in.us-east-1.rds.amazonaws.com
      database: retailstore

      secret:
        create: false
        name: catalog-db

orders:
  app:
    persistence:
      provider: postgres
      endpoint: project-bedrock-postgres.cop8qmuak7in.us-east-1.rds.amazonaws.com
      database: retailstore

      secret:
        create: false
        name: orders-db

    messaging:
      provider: rabbitmq

cart:
  app:
    persistence:
      provider: dynamodb

      dynamodb:
        tableName: project-bedrock-carts
        createTable: false

ui:
  ingress:
    enabled: true
    className: alb

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip

    hosts:
      - project-bedrock.54.165.244.253.nip.io
